// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Books": book Resource Client
//
// Command:
// $ goagen
// --design=github.com/jaredwarren/redeam/design
// --out=$(GOPATH)/src/github.com/jaredwarren/redeam
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// CreateBookPath computes a request path to the create action of book.
func CreateBookPath() string {

	return fmt.Sprintf("/books")
}

// Create a new book
func (c *Client) CreateBook(ctx context.Context, path string, payload *BookPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateBookRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateBookRequest create the request corresponding to the create action endpoint of the book resource.
func (c *Client) NewCreateBookRequest(ctx context.Context, path string, payload *BookPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteBookPath computes a request path to the delete action of book.
func DeleteBookPath(bookID int) string {
	param0 := strconv.Itoa(bookID)

	return fmt.Sprintf("/books/%s", param0)
}

// DeleteBook makes a request to the delete action endpoint of the book resource
func (c *Client) DeleteBook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteBookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteBookRequest create the request corresponding to the delete action endpoint of the book resource.
func (c *Client) NewDeleteBookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ListBookPath computes a request path to the list action of book.
func ListBookPath() string {

	return fmt.Sprintf("/books")
}

// Retrieve all books.
func (c *Client) ListBook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListBookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListBookRequest create the request corresponding to the list action endpoint of the book resource.
func (c *Client) NewListBookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowBookPath computes a request path to the show action of book.
func ShowBookPath(bookID int) string {
	param0 := strconv.Itoa(bookID)

	return fmt.Sprintf("/books/%s", param0)
}

// Show a book.
func (c *Client) ShowBook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowBookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowBookRequest create the request corresponding to the show action endpoint of the book resource.
func (c *Client) NewShowBookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateBookPath computes a request path to the update action of book.
func UpdateBookPath(bookID int) string {
	param0 := strconv.Itoa(bookID)

	return fmt.Sprintf("/books/%s", param0)
}

// Change book data
func (c *Client) UpdateBook(ctx context.Context, path string, payload *BookPayload, contentType string) (*http.Response, error) {
	req, err := c.NewUpdateBookRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateBookRequest create the request corresponding to the update action endpoint of the book resource.
func (c *Client) NewUpdateBookRequest(ctx context.Context, path string, payload *BookPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
