consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Book:
    description: A Book (default view)
    example:
      author: Aut consequatur in et rerum ab inventore.
      created_at: 1994-10-12T16:31:10Z
      id: 8.35359e+18
      publish_date: 1978-08-18T03:06:31Z
      publisher: Aliquam architecto molestiae et aut et et.
      rating: 1
      status: CheckedOut
      title: Dicta dolorem sequi sunt impedit.
      updated_at: 2006-12-19T23:26:46Z
    properties:
      author:
        description: Author(s) of the book
        example: Aut consequatur in et rerum ab inventore.
        type: string
      created_at:
        description: Date of creation
        example: 1994-10-12T16:31:10Z
        format: date-time
        type: string
      id:
        description: Book ID
        example: 8.35359e+18
        format: int64
        type: integer
      publish_date:
        description: Date of publication
        example: 1978-08-18T03:06:31Z
        format: date-time
        type: string
      publisher:
        description: Publisher of the book
        example: Aliquam architecto molestiae et aut et et.
        type: string
      rating:
        default: 1
        example: 1
        maximum: 3
        minimum: 1
        type: integer
      status:
        enum:
        - CheckedIn
        - CheckedOut
        example: CheckedOut
        type: string
      title:
        description: Book title
        example: Dicta dolorem sequi sunt impedit.
        type: string
      updated_at:
        description: Date of last change
        example: 2006-12-19T23:26:46Z
        format: date-time
        type: string
    required:
    - id
    - created_at
    - updated_at
    title: 'Mediatype identifier: application/vnd.book+json; view=default'
    type: object
  BookCollection:
    description: BookCollection is the media type for an array of Book (default view)
    example:
    - author: Aut consequatur in et rerum ab inventore.
      created_at: 1994-10-12T16:31:10Z
      id: 8.35359e+18
      publish_date: 1978-08-18T03:06:31Z
      publisher: Aliquam architecto molestiae et aut et et.
      rating: 1
      status: CheckedOut
      title: Dicta dolorem sequi sunt impedit.
      updated_at: 2006-12-19T23:26:46Z
    items:
      $ref: '#/definitions/Book'
    title: 'Mediatype identifier: application/vnd.book+json; type=collection; view=default'
    type: array
  BookPayload:
    example:
      author: Iusto dolores non eum omnis eius tempore.
      id: 2.9969716e+18
      publish_date: 1978-03-06T14:32:30Z
      publisher: Consequuntur sit omnis voluptas ut voluptas quisquam.
      rating: 1
      status: CheckedIn
      title: Aut illum nam.
    properties:
      author:
        description: Author(s) of the book
        example: Iusto dolores non eum omnis eius tempore.
        type: string
      id:
        description: Book ID
        example: 2.9969716e+18
        format: int64
        type: integer
      publish_date:
        description: Date of publication
        example: 1978-03-06T14:32:30Z
        format: date-time
        type: string
      publisher:
        description: Publisher of the book
        example: Consequuntur sit omnis voluptas ut voluptas quisquam.
        type: string
      rating:
        default: 2
        example: 1
        maximum: 3
        minimum: 1
        type: integer
      status:
        enum:
        - CheckedIn
        - CheckedOut
        example: CheckedIn
        type: string
      title:
        description: Book title
        example: Aut illum nam.
        type: string
    title: BookPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
externalDocs:
  description: Books Service
  url: http://jlwarren1.com
host: localhost:8080
info:
  contact:
    email: jlwarren1@gmail.com
    name: Jared Warren
    url: http://jlwarren1.com
  description: Redeam.com Book Test
  title: Redeam.com Books
  version: ""
paths:
  /_ah/health:
    get:
      description: Health check API
      operationId: health#health
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: health health
      tags:
      - health
  /books:
    get:
      description: Retrieve all books.
      operationId: book#list
      produces:
      - application/vnd.book+json; type=collection
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/BookCollection'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: list book
      tags:
      - book
    post:
      description: Create a new book
      operationId: book#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/BookPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: href to created resource
              pattern: /books/[0-9]+
              type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create book
      tags:
      - book
  /books/{bookID}:
    delete:
      operationId: book#delete
      parameters:
      - description: Book ID
        in: path
        minimum: 1
        name: bookID
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: delete book
      tags:
      - book
    get:
      description: Show a book.
      operationId: book#show
      parameters:
      - description: Book ID
        in: path
        minimum: 1
        name: bookID
        required: true
        type: integer
      produces:
      - application/vnd.book+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Book'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: show book
      tags:
      - book
    put:
      description: Change book data
      operationId: book#update
      parameters:
      - description: Book ID
        in: path
        name: bookID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/BookPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: update book
      tags:
      - book
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Book'
schemes:
- http
swagger: "2.0"
