// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Books": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/jaredwarren/redeam/design
// --out=$(GOPATH)/src/github.com/jaredwarren/redeam
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// BookHref returns the resource href.
func BookHref(bookID interface{}) string {
	parambookID := strings.TrimLeftFunc(fmt.Sprintf("%v", bookID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/books/%v", parambookID)
}
